# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.TextField(max_length=200)),
                ('team_detail', models.TextField(max_length=4000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='team',
            field=models.ManyToManyField(to='polls.Teams'),
        ),
    ]
