# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180306_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
