# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180306_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
