# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180302_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_id',
            field=models.AutoField(default='0000', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.AutoField(default='0000000', primary_key=True, serialize=False),
        ),
    ]
